### PR TITLE
Add Appveyor integration

### PR DESCRIPTION
**Pull request by simondel**
Hi! Appveyor allows you to build your open source project for free so I added a config to get you guys up and running. 

You still have go allow Appveyor to integrate with Augurk/Augurk.CommandLine but after that your build should succeed and you could add a build-badge to show that your build is passing.

### CODE REVIEW

**Comment by marktaling** [comment]
@jmezach Did you take a look at this? I think you are better qualified to evaluate this than I am.

**Comment by simondel** [comment]
Odd. I expected the appveyor link to be https://ci.appveyor.com/project/augurk/augurk-commandline and not https://ci.appveyor.com/project/jmezach/augurk-commandline

**Comment by simondel** [comment]
@jmezach Could you give me the ID of the `Webhook URL` specified in https://ci.appveyor.com/project/simondel/augurk-commandline/settings? I'll fix the master branch badge :)

**Comment by jmezach** [comment]
@simondel I've renamed the account to Augurk so it should be https://ci.appveyor.com/project/augurk/augurk-commandline now.

WebHook URL is: https://ci.appveyor.com/api/github/webhook?id=elxscd2cr60jkx35

**Comment by simondel** [comment]
Nice! I fixed the badge to show the status of your master branch 👍

**Comment by jmezach** [comment]
Awesome. I'll merge this in. Will probably need to tweak the build definition a bit, but for now this looks fine :).

**Comment by simondel** [comment]
Cool! You can use the web interface of AppVeyor to make changes and go to `Settings -> Export YAML` to see the YAML code.

**Pull request merged**
